### ISSUE TITLE
Cannot import name 'assert_utf8_env' from 'mitmproxy.tools.main'

### ISSUE THREAD

**Issue by mieucun123** [rachmadaniHaryono/mitmproxy-image#4]
**Describe the bug**
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy-image", line 5, in <module>
    from mitmproxy_image.cli import main
  File "/usr/local/lib/python3.9/dist-packages/mitmproxy_image/cli.py", line 25, in <module>
    from mitmproxy.tools.main import assert_utf8_env, process_options
ImportError: cannot import name 'assert_utf8_env' from 'mitmproxy.tools.main' (/usr/local/lib/python3.9/dist-packages/mitmproxy/tools/main.py)

**To Reproduce**
1. run command: mitmproxy-image

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/57987868/171610218-1b04c552-556e-4345-ad59-bf82c7201231.png)

**System (please complete the following information):**
- `mitmproxy-image` version: 8.1.0
- Python version: 3.9.5
- OS: Linux

**Additional context**

**Comment by rachmadaniHaryono** [comment]
If you can run from source, you can edit the assert_utf8_env import section and comment out the function call

Unfortunate I will not have my PC for weeks/months and can't make the fix

Also I don't recommend using sudo to run python program, and recommend to use pipx or virtual env

**Comment by rachmadaniHaryono** [comment]
this should be fixed on 1.5.1

if there is still issue, please reopen this issue
